from multiprocessing.managers import BaseManager
from gdpc import Editor, Block

editor=Editor(buffering=True)

def bamboo(x,y,z):
    editor.placeBlock((x+0,y+0,z+0),Block("minecraft:grass_block[snowy=false]"))
    editor.placeBlock((x+0,y+0,z+1),Block("minecraft:grass_block[snowy=false]"))
    editor.placeBlock((x+0,y+1,z+0),Block("minecraft:bamboo[age=1,leaves=none,stage=0]"))
    editor.placeBlock((x+0,y+1,z+1),Block("minecraft:bamboo[age=1,leaves=none,stage=0]"))
    editor.placeBlock((x+0,y+2,z+0),Block("minecraft:bamboo[age=1,leaves=none,stage=0]"))
    editor.placeBlock((x+0,y+2,z+1),Block("minecraft:bamboo[age=1,leaves=none,stage=0]"))
    editor.placeBlock((x+0,y+3,z+0),Block("minecraft:bamboo[age=1,leaves=none,stage=0]"))
    editor.placeBlock((x+0,y+3,z+1),Block("minecraft:bamboo[age=1,leaves=none,stage=0]"))
    editor.placeBlock((x+0,y+4,z+0),Block("minecraft:bamboo[age=1,leaves=none,stage=0]"))
    editor.placeBlock((x+0,y+4,z+1),Block("minecraft:bamboo[age=1,leaves=none,stage=0]"))
    editor.placeBlock((x+0,y+5,z+0),Block("minecraft:bamboo[age=1,leaves=none,stage=0]"))
    editor.placeBlock((x+0,y+5,z+1),Block("minecraft:bamboo[age=1,leaves=none,stage=0]"))
    editor.placeBlock((x+0,y+6,z+0),Block("minecraft:bamboo[age=1,leaves=small,stage=0]"))
    editor.placeBlock((x+0,y+6,z+1),Block("minecraft:bamboo[age=1,leaves=small,stage=0]"))
    editor.placeBlock((x+0,y+7,z+0),Block("minecraft:bamboo[age=1,leaves=large,stage=0]"))
    editor.placeBlock((x+0,y+7,z+1),Block("minecraft:bamboo[age=1,leaves=large,stage=0]"))
    editor.placeBlock((x+0,y+8,z+0),Block("minecraft:bamboo[age=1,leaves=large,stage=0]"))
    editor.placeBlock((x+0,y+8,z+1),Block("minecraft:bamboo[age=1,leaves=large,stage=0]"))
    editor.placeBlock((x+0,y+9,z+0),Block("minecraft:air"))
    editor.placeBlock((x+0,y+9,z+1),Block("minecraft:air"))
    editor.placeBlock((x+0,y+10,z+0),Block("minecraft:air"))
    editor.placeBlock((x+0,y+10,z+1),Block("minecraft:air"))
    editor.placeBlock((x+1,y+0,z+0),Block("minecraft:grass_block[snowy=false]"))
    editor.placeBlock((x+1,y+0,z+1),Block("minecraft:grass_block[snowy=false]"))
    editor.placeBlock((x+1,y+1,z+0),Block("minecraft:bamboo[age=1,leaves=none,stage=0]"))
    editor.placeBlock((x+1,y+1,z+1),Block("minecraft:bamboo[age=1,leaves=none,stage=0]"))
    editor.placeBlock((x+1,y+2,z+0),Block("minecraft:bamboo[age=1,leaves=none,stage=0]"))
    editor.placeBlock((x+1,y+2,z+1),Block("minecraft:bamboo[age=1,leaves=none,stage=0]"))
    editor.placeBlock((x+1,y+3,z+0),Block("minecraft:bamboo[age=1,leaves=none,stage=0]"))
    editor.placeBlock((x+1,y+3,z+1),Block("minecraft:bamboo[age=1,leaves=none,stage=0]"))
    editor.placeBlock((x+1,y+4,z+0),Block("minecraft:bamboo[age=1,leaves=none,stage=0]"))
    editor.placeBlock((x+1,y+4,z+1),Block("minecraft:bamboo[age=1,leaves=small,stage=0]"))
    editor.placeBlock((x+1,y+5,z+0),Block("minecraft:bamboo[age=1,leaves=none,stage=0]"))
    editor.placeBlock((x+1,y+5,z+1),Block("minecraft:bamboo[age=1,leaves=large,stage=0]"))
    editor.placeBlock((x+1,y+6,z+0),Block("minecraft:bamboo[age=1,leaves=none,stage=0]"))
    editor.placeBlock((x+1,y+6,z+1),Block("minecraft:bamboo[age=1,leaves=large,stage=0]"))
    editor.placeBlock((x+1,y+7,z+0),Block("minecraft:bamboo[age=1,leaves=none,stage=0]"))
    editor.placeBlock((x+1,y+7,z+1),Block("minecraft:air"))
    editor.placeBlock((x+1,y+8,z+0),Block("minecraft:bamboo[age=1,leaves=small,stage=0]"))
    editor.placeBlock((x+1,y+8,z+1),Block("minecraft:air"))
    editor.placeBlock((x+1,y+9,z+0),Block("minecraft:bamboo[age=1,leaves=large,stage=0]"))
    editor.placeBlock((x+1,y+9,z+1),Block("minecraft:air"))
    editor.placeBlock((x+1,y+10,z+0),Block("minecraft:bamboo[age=1,leaves=large,stage=0]"))
    editor.placeBlock((x+1,y+10,z+1),Block("minecraft:air"))


